"""Permission-controlled generic Forge tool framework."""

from forge.tools.builtin import (
    PROJECT_TOOL_NAMES,
    READ_ONLY_TOOL_NAMES,
    WRITE_TOOL_NAMES,
    create_assist_repository_policy,
    create_assist_repository_registry,
    create_readonly_repository_policy,
    create_readonly_repository_registry,
    create_repository_registry,
)
from forge.tools.executor import ToolExecutor
from forge.tools.git import GitDiffTool, GitStatusTool
from forge.tools.paths import (
    WorkspacePathError,
    resolve_workspace_path,
    resolve_workspace_write_path,
    workspace_relative_path,
)
from forge.tools.permissions import (
    AllowAllPolicy,
    DenyAllPolicy,
    PermissionPolicy,
    RuleBasedPolicy,
)
from forge.tools.project import (
    MAX_PROCESS_OUTPUT_BYTES,
    PreparedProjectCommand,
    ProjectCommandTool,
)
from forge.tools.registry import ToolRegistrationError, ToolRegistry
from forge.tools.repository import (
    MAX_READ_BYTES,
    MAX_SEARCH_FILE_BYTES,
    MAX_SEARCH_RESULTS,
    ListDirectoryTool,
    ReadFileTool,
    SearchFilesTool,
)
from forge.tools.repository_write import (
    MAX_WRITE_BYTES,
    ApplyPatchTool,
    MutationPreview,
    WriteFileTool,
    preview_repository_mutation,
)
from forge.tools.tool import Tool, ToolError
from forge.tools.types import (
    ArgumentSchema,
    ArgumentSpec,
    ArgumentType,
    ExecutionContext,
    InvocationApproval,
    PermissionDecision,
    ToolCapability,
    ToolErrorKind,
    ToolEvidence,
    ToolExecutionMetadata,
    ToolInvocation,
    ToolMetadata,
    ToolResult,
    ToolResultStatus,
    ToolRisk,
    ToolValidationError,
)

__all__ = [
    "AllowAllPolicy",
    "ArgumentSchema",
    "ArgumentSpec",
    "ArgumentType",
    "ApplyPatchTool",
    "DenyAllPolicy",
    "ExecutionContext",
    "InvocationApproval",
    "GitDiffTool",
    "GitStatusTool",
    "ListDirectoryTool",
    "MAX_READ_BYTES",
    "MAX_SEARCH_FILE_BYTES",
    "MAX_SEARCH_RESULTS",
    "MAX_WRITE_BYTES",
    "MutationPreview",
    "PermissionDecision",
    "PermissionPolicy",
    "RuleBasedPolicy",
    "READ_ONLY_TOOL_NAMES",
    "PROJECT_TOOL_NAMES",
    "MAX_PROCESS_OUTPUT_BYTES",
    "PreparedProjectCommand",
    "ProjectCommandTool",
    "WRITE_TOOL_NAMES",
    "ReadFileTool",
    "SearchFilesTool",
    "Tool",
    "ToolError",
    "ToolErrorKind",
    "ToolCapability",
    "ToolEvidence",
    "ToolExecutionMetadata",
    "ToolExecutor",
    "ToolInvocation",
    "ToolMetadata",
    "ToolRegistrationError",
    "ToolRegistry",
    "ToolResult",
    "ToolResultStatus",
    "ToolRisk",
    "ToolValidationError",
    "WorkspacePathError",
    "WriteFileTool",
    "create_assist_repository_policy",
    "create_assist_repository_registry",
    "create_readonly_repository_policy",
    "create_readonly_repository_registry",
    "create_repository_registry",
    "resolve_workspace_path",
    "resolve_workspace_write_path",
    "preview_repository_mutation",
    "workspace_relative_path",
]
